### ISSUE TITLE
 No module named 'config'

### ISSUE THREAD

**Issue by SoliveTech** [bastianwandt/DiffPose#1]
Thanks for your insightful paper and the released neat code! I am trying to train the nodel under the guidence in readme.md, but met some problem like below :

Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from models.trainer import Trainer
  File "/home/qmt/m/DiffPose-main/models/trainer.py", line 26, in <module>
    from utils.data_utils import (
  File "/home/qmt/m/DiffPose-main/utils/data_utils.py", line 3, in <module>
    import config as c
ModuleNotFoundError: No module named 'config'

and I can't find the file config.py, how can I fix this problem?

**Comment by karlHolmquist** [comment]
Thank you and apologies for that, we accidentally omitted that file. It should have been added now.

Let me know if there's any other issues. I will try to release our pre-trained weights in the next couple weeks as well.

**Comment by SoliveTech** [comment]
Thank you very much for your prompt reply and help! And I found this problem while running train.py:

Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from data.data_h36m import H36MDataset, H36MDatasetH5, PW3DDatasetH5
ModuleNotFoundError: No module named 'data.data_h36m'

I did not file 'data. Data_h36m', so I guess it is not properly produce heatmaps, so I follow the direction of _DiffPose/data preprocessing/README.md_ to unzip the download data, But the last step described a  'pose_detection.py' file, I don't know where to find it. Can you give me some advice and your directory structure for the data as an inference？

Many thanks！

**Comment by karlHolmquist** [comment]
Thank you for the report, data.data_h36m should be data.dataset (fixed in main now)

The data preprocessing README has also been updated now, pose_detection.py was renamed to [data/preprocessing/H36M.py] (Similar naming schemes for the other datasets)

**Comment by SoliveTech** [comment]
Thank you for your patience and modification! It is a great honor to follow your related work！
